# Generated by Django 4.0.6 on 2023-02-03 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='follower',
            new_name='user',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
