# Generated by Django 4.0.6 on 2023-02-03 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_follower_follow_user_delete_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='picture',
            new_name='image',
        ),
    ]
