# Generated by Django 4.0.6 on 2023-02-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_rename_likes_post_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
