# Generated by Django 4.0.6 on 2023-02-03 12:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0008_post_like2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like2',
        ),
        migrations.AddField(
            model_name='post',
            name='like2',
            field=models.ManyToManyField(null=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
