# Generated by Django 4.0.6 on 2023-02-03 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_remove_post_like2_post_like2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
