# Generated by Django 4.0.6 on 2023-02-03 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_remove_post_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='like2',
            new_name='likes',
        ),
    ]
